### ISSUE TITLE
Can't display recent commands

### ISSUE THREAD

**Issue by tobegit3hub** [dvorka/hstr#110]
I can `history |grep` all the commands but `hh` only displays the previous ones.

**Comment by dvorka** [comment]
'hh' is based on C libraries that read/manipulate ~/.bash_history. The thing is that BASH keeps recent commands in memory only - they are available through 'history' command. Recent commands are flushed to disc (.bash_history) at the end of BASH session. However, you may force flushing of in memory items to disc for instance using:

> export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
 
'hh' comes with suggested configuration that should be appended at then end of .bashrc in order to get most of 'hh':

> hh --show-configuration

gives something like:

```
export HH_CONFIG=hicolor         # get more colors
shopt -s histappend              # append new history items to .bash_history
export HISTCONTROL=ignorespace   # leading space hides commands from history
export HISTFILESIZE=10000        # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"   # mem/file sync
# if this is interactive shell, then bind hh to Ctrl-r
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hh \C-j"'; fi
```

... so that you can:

> hh --show-configuration >> ~/.bashrc

**Comment by tobegit3hub** [comment]
Thanks @dvorka and this is reasonable :smiley:
