### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by casimir** [dvorka/hstr#137]
Since ncurses and Archlinux seem to have a difficult relationship ([see comments](https://aur.archlinux.org/packages/hstr-git)), I made a new [PKGBUILD](https://github.com/casimir/contrib-packages/blob/master/hstr-bin/PKGBUILD) using your binary releases: https://aur.archlinux.org/packages/hstr-bin.

Note that I don't intend to replace the git package, I know some people prefer compiling sources directly (avoiding binaries or following tip). I'll try to keep up with your Github releases.

I filed a request to merge https://aur.archlinux.org/packages/hh with https://aur.archlinux.org/packages/hstr-git too since it was outdated and redundant.

**Comment by casimir** [comment]
I guess @fastgar is taking this over.

**Comment by dvorka** [comment]
@fastgar @casimir I appreciate your contribution and help. If there is anything I can do, please let me know.

**Comment by fastgar** [comment]
Hi the binary is not compatible with Arch anymore due to an ncurses update.

hh: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

/usr/lib: lrwxrwxrwx   1 root root    18 15. Sep 05:47 libncursesw.so.6 -> libncursesw.so.6.0

don't know at which state the other distro's are with ncurses version.

The hstr-git package should run fine after updating it, cause it recompiles everything against the new ncurses version, without problem.
