### ISSUE TITLE
Possibility to remove items without confirming?

### ISSUE THREAD

**Issue by heeboA** [dvorka/hstr#238]
It would be nice to be able to delete entries from history by just pressing del without having to confirm. Can I configure this somewhere?

**Comment by dvorka** [comment]
There was no confirmation in the past, but users asked for it so I implemented that. I agree that it might be bothering - I will add and option that will disable y/n prompt.

**Comment by heeboA** [comment]
Thanks for the quick response! Looking forward to the update :+1:

**Comment by dvorka** [comment]
Use `HH_CONFIG=noconfirm` to disable confirmation(s).

**Comment by 1-61803** [comment]
`HH_CONFIG=noconfirm` doesn't work in `bash` 4, i.e., it keeps asking for confirmation. Furthermore, it strangely seems to disable some theme colors in `OS X`'s `Terminal`.

**Comment by 1-61803** [comment]
@dvorka, `HH_CONFIG=noconfirm` doesn't work in `bash` 4, i.e., it keeps asking for confirmation. Furthermore, it strangely seems to disable some theme colors in `OS X`'s `Terminal`.

**Comment by dvorka** [comment]
@1-61803 `HH_CONFIG=noconfirm` is not released via PPA yet (you need to build it from source code). Also colors are disabled by default - to keep colors (when reconfiguring) you need to use `HH_CONFIG=noconfirm,hicolor`.

**Comment by 1-61803** [comment]
@dvorka, I built it from source and it works, but it seems to delete the last occurrence, while others, if existent, remain. This could be implemented like this: if there's one occurrence, `DEL` deletes it, else if there're others the interface asks for confirmation with `DEL` (second press) or the user dismisses it with `ESC` or `C-g`.
And deleting in `hstr` doesn't remove the entries from history in the current session as reported in #250.

**Comment by dvorka** [comment]
@1-61803 I really appreciate that you invested your time in building `hstr`! `hstr` aims to delete **all** occurrences of given command from history - IMO it makes no sense to delete just one occurrence as it would have impact on the rank in `hstr` ordering metrics only.

Regarding the *removal of some/all entries* issue - I guess that it's related to the way how `hstr` works. Please indulge me, I didn't find a better way: `hstr` loads `.bash_history` file managed by BASH (I use history library to load/save/manage it). Unfortunately BASH keeps history of command in memory and in certain situations (and on demand) it flushes this list to filesystem (`.bash_history` file). In order to ensure that `hstr` works with up to date history you need to have in your configuration (`.bashrc`) the following statement:
```
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
```
It flushes command history and then reloads it before every shell command execution - see `help history` and `hstr` documentation. Yes, it's inefficient and it's up to you whether it's worth it or not.

**Comment by 1-61803** [comment]
I do have `PROMPT_COMMAND` set, but it still doesn't work as described in #250. Does it in your system/s?
Since it sometimes deletes, say 35 entries, but then maybe 3 still remain in `hstr`, I kind of wonder if it has something to do with the history size, mine being `HISTFILESIZE=10000`.

**Comment by 1-61803** [comment]
@dvorka, I do have `PROMPT_COMMAND` set, but it still doesn't work as described in #250. Does it in your system/s?
Since it sometimes deletes, say 35 entries, but then maybe 3 still remain in `hstr`, I kind of wonder if it has something to do with the history size, mine being `HISTFILESIZE=10000`.

**Comment by dvorka** [comment]
@1-61803 Unfortunately I'm not able to reproduce #250 on any of my machines. I also went through the C code and didn't find any obvious reason why big history should be trimmed (BTW I use the same history limit as you i.e. 10000) - you may check that there are no limits in the function that deletes entries from the history yourself: https://github.com/dvorka/hstr/blob/master/src/hstr_history.c#L221

Therefore the most probable hypothesis is that the problem is in an inconsistency between memory and filesystem history.

Reproducible description for #250 would really help. I mean something like: use `.bash_history` with content listed below, start new Bash session, do command C1, do command C2, run `hstr`, delete C2, check `.bash_history`/run `history`/run `hstr` to see remaining entries (e.g. it might be that remaining entries are not visible in `hstr`, but can be seen in `history`).

**Comment by dvorka** [comment]
Actually there might be another **difficult to spot** cause of the remaining-entries problem e.g. a (trailing) whitespace in the command - `hstr` requires exact match i.e. `ls` and `ls ` are different commands, similarly `echo x` and `echo  x` are different as well.

**Comment by 1-61803** [comment]
@dvorka
Re inconsistency between `history` and `hstr`, `history -c; history -r` yields the following.
```
$ history | tail -n 3
   12  history | tail -n 3
   13  history | tail -n 3
   14  history | tail -n 3
$ echo test
test
$ echo test2
test2
$ echo test3
test3
$ history | tail -n 3
   16  echo test2
   17  echo test3
   18  history | tail -n 3
$ history -c; history -r
$ history | tail -n 3
   12  history | tail -n 3
   13  history | tail -n 3
   14  history | tail -n 3
```

Re remaining entries, the matches where exact.

**Comment by 1-61803** [comment]
@dvorka
Re inconsistency between `history` and `hstr`, `history -c; history -r` yields the following.
```
$ history | tail -n 3
   12  history | tail -n 3
   13  history | tail -n 3
   14  history | tail -n 3
$ echo test
test
$ echo test2
test2
$ echo test3
test3
$ history | tail -n 3
   16  echo test2
   17  echo test3
   18  history | tail -n 3
$ history -c; history -r
$ history | tail -n 3
   12  history | tail -n 3
   13  history | tail -n 3
   14  history | tail -n 3
```
Re remaining entries, the matches were exact.
