### ISSUE TITLE
.bash_history_favorites

### ISSUE THREAD

**Issue by zvezdochiot** [dvorka/hstr#269]
Please add .bash_history_favorites, as a history-independent collection of commands.

**Comment by xaizek** [comment]
What would be the difference between that and `.hh_favorites` except for the name?

**Comment by zvezdochiot** [comment]
I apologize. I did not notice the elephant.

**Comment by zvezdochiot** [comment]
Favorites commands in a separate list? What for?

**Comment by dvorka** [comment]
`.hh_favorites` is maintained independently because the life-cycle of favorite commands is different from history items. History is limited in size (new entries replace old entries), while favorite commands require action to add/remove new entry. You could maintain favorites using `#` tags, but they can disappear. You can synchronize/share/transfer favorites file among your (virtual) machines (without a need to have a history there).

**Comment by zvezdochiot** [comment]
That's right. But the search for a common list (favorites + history) is of interest. So far, no such functionality. Is it possible?

**Comment by dvorka** [comment]
Do you mean searching of favorites and history union (in the same list)?

**Comment by zvezdochiot** [comment]
Quite right. I would like to have a complete list of commands. Regardless of whether they are listed as favorites or recently used.
