### ISSUE TITLE
matching on +%s causes segfault

### ISSUE THREAD

**Issue by bdantas** [dvorka/hstr#271]
I installed hh version 1.2-1 using the .deb from your repository, following the instructions [here](https://github.com/dvorka/hstr/blob/master/INSTALLATION.md#debianmint). My OS is Devuan ASCII (fork of Debian Stretch) in case it matters. The suggest box works great and is the biggest enhancement to my terminal emulator in many years. Thank you.

After using the suggest box for a few months, today I found something very strange: If I bring up the suggest box with Control + r as usual then search for `en` (for example, when looking for commands containing the string "english"), the suggest box crashes with a segmentation fault. Searching for `ex` (for example, when looking for commands containing the string "exim"), `En`, `EN`, `Ex`, or `EX` also causes a segmentation fault. All the other letter combinations I've tried work fine.

Can anyone else reproduce this problem? Is there a fix?

**Comment by dvorka** [comment]
The `sigsegv` is most probably caused by an entry in your history which contains `en` and/or `ex` substring. (Un)fortunately I don't expect this is reproducible by other users. Perhaps it may be a looong line, a line with a special character, etc. and HSTR doesn't handles it well.

Could you please grep your history and try to identify a suspicious/problematic entry? (I don't need to see that line (your privacy), just need to reproduce it on something similar)
```bash
grep ~/.bash_history
```
Could you please run the following commands (version, OS version, and strace of the crash) and attach output to this bug?

```
hh --version   
uname -a
strace hh 2 > error.log # let HSTR crash by searching for en
```
Thank you in advance!

**Comment by bdantas** [comment]
Thanks for the insights, dvorka. I narrowed down the cause for the crashes to having this command in my history: `date +%s -r expenses.txt`
No crashes after I delete that from my bash history.

`hh --version` just brings up the suggest box, hope this helps instead:
```
$ apt list --installed | grep hh
hh/now 1.2-1 amd64 [installed,local]
```
```
$ uname -a
Linux thinkpad 4.16.2-gnu #1 SMP Thu Apr 12 13:27:37 UTC 2018 x86_64 GNU/Linux
```

strace of a crash is [here](https://pastebin.com/KmhqvR1j)

**Comment by bdantas** [comment]
It seems that hh doesn't like the string `+%s`

**Comment by dvorka** [comment]
I just verified that this problem is **not** reproducible on the latest release.

I guess that you have very old version - I do not sustain `.deb` repository/packages. Let me build deb and/or create my own PPA repository.

I will build new `.deb`, test it on Debian Stretch and let you know. Please stay tuned.

**Comment by bdantas** [comment]
I liked the old version's color scheme (gray background etc). Is there a way to enjoy the same color scheme while using the new version?

**Comment by bdantas** [comment]
Haha, I think it's the "buggy" look that I liked. No problem. I'll get used to the new look.

I'll keep an eye out for your Debian PPA.

Happy hacking!
