### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by isanych** [dvorka/hstr#395]
As there are no 20.04 packages in PPA, I was using ubuntu build instructions, pkg-config is required but not mentioned in dependencies, installing pkg-config before using automake or executing `autoreconf -i -f` after resolves an issue.

**Comment by emk2203** [comment]
As an add-on, please add 20.04 to the PPA. It would be very helpful to keep a clean system without too much self-compiled stuff.

**Comment by chris2k20** [comment]
Really need HSTR on my Ubuntu 20.04, too.. Without it I don`t have a good documentation ;)

BTW thank you for this great program! I use it everyday on every Linux System. 🙏 

```
sudo add-apt-repository ppa:ultradvorka/ppa && sudo apt-get update && sudo apt-get install hstr && hstr --show-configuration >> ~/.bashrc && . ~/.bashrc
 Admin utilities and productivity applications.
 More info: https://launchpad.net/~ultradvorka/+archive/ubuntu/ppa
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease    
Ign:3 http://ppa.launchpad.net/ultradvorka/ppa/ubuntu focal InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu focal InRelease
Hit:5 http://de.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://de.archive.ubuntu.com/ubuntu focal-backports InRelease
Err:7 http://ppa.launchpad.net/ultradvorka/ppa/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/ultradvorka/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by dvorka** [comment]
I'm still on 18.04 - installing 20.04 VM and will fix the build and prepare PPA. I apologize for the delay.

**Comment by dvorka** [comment]
@isanych @emk2203 @Armatorix I just finished release of HSTR for HSTR 20.04 - please install from PPA.

**Comment by chris2k20** [comment]
Installation successfully finished via PPA on my 20.04, thank you very much!!! :+1: 

If someone wants to install HSTR via ansible, here is my little ansible playbook (rename it to pb_localhost_hstr.yml): [pb_localhost_hstr.txt](https://github.com/dvorka/hstr/files/4626553/pb_localhost_hstr.txt)

Install ansible (`apt install ansible`). Afterwards you need to open a shell,  run `sudo -i ` and exit (so that you don´t need to enter PW for this session again and ansible can become root). Now run the downloaded playbook: `ansible-playbook pb_localhost_hstr.yml`
